### ISSUE TITLE
Using graphreg() or plotreg() options

### ISSUE THREAD

**Issue by ericmelse** [asjadnaqvi/stata-arcplot#7]
Dear Asjad,
Is it correct that your `arcplot` command does not accept options to control the attributes of the graph or plot region?
I.e. using `graphregion()` or `plotregion()` 
Like:
```
use "https://github.com/asjadnaqvi/stata-arcplot/blob/main/data/trade_2022.dta?raw=true", clear

arcplot value, from(ex_region) to(im_region) graphregion(c(yellow))
```
results in:
```
option graphregion() not allowed
r(198);
```
which appears to me rather odd.

**Comment by asjadnaqvi** [comment]
fixed!
