### ISSUE TITLE
-arcplot- asks input var to be named "value"

### ISSUE THREAD

**Issue by GPapad-gr** [asjadnaqvi/stata-arcplot#8]
Hi Asjad,

And thanks for creating these amazing commands helping create such magnificent plots with Stata! Kudos!

I was trying to use -arcplot- and I got the following error message:

```
* Example code
use "https://github.com/asjadnaqvi/stata-arcplot/blob/main/data/trade_2022.dta?raw=true", clear

rename value y // rename variable to showcase the issue

arcplot y, from( ex_region ) to( im_region )

variable value not found
r(111);

```

However, when the input to -arcplot- is named "value", then the command works like a charm.

I've stumbled upon this issue when trying to plot some variables of my own which was not originally named "value". It's not a major issue, meaning that I circumvented it by renaming the variable of interest to "value", but I thought of mentioning it. In fact, it occurred in both 1.3 and 1.4 versions of -arcplot-.

Kind regards,
Georgios

**Comment by asjadnaqvi** [comment]
THank you for reporting this! Reinstall the latest version to fix this bug:

```
net install arcplot, from("https://raw.githubusercontent.com/asjadnaqvi/stata-arcplot/main/installation/") replace
```

**Comment by GPapad-gr** [comment]
Thanks Asjad, done! (And what a swift answer!)
